### ISSUE TITLE
No window is created.

### ISSUE THREAD

**Issue by Wicked0ne** [ziyasal/Caliburn.Metro#6]
Hi. After installing Caliburn.Metro via NuGet and copying all the files from https://github.com/ziyasal/Caliburn.Metro/tree/master/Caliburn.Metro.Sample (of course changing the namespaces correctly etc etc). The application fails to compile with this message: Could not locate any instances of contract Caliburn.Micro.IWindowManager. I'm not sure how to fix this. Any help is appreciated!

**Comment by ziyasal** [comment]
Hi @Wicked0ne , thanks for your feedback, I tried to reproduce problem but it works well.
Here is my steps;
- Created blank solution
- Added Sample project to solution
- Performed renaming
- Install Caliburn.Metro package

You can find my sample [here](https://dl.dropboxusercontent.com/u/33940399/CMSample.7z)
