### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by petersondrew** [ziyasal/Caliburn.Metro#7]
Hi there,

I noticed that you haven't added a license for this project. Unfortunately, with the way copyright works in most countries, without specifying an open source license, no one technically has the right to use or redistribute your code.

Would you mind adding an acceptable [license](http://opensource.org/licenses) to this project? If you're unsure and want some input, [MIT](http://opensource.org/licenses/MIT) is a super simple and lenient license.

Thanks so much!

**Comment by ziyasal** [comment]
Hi @petersondrew
I forgot it, thank you for notify.
